### ISSUE TITLE
Patterns from .gitignore in subdirectory should be prefixed with that subdirectory

### ISSUE THREAD

**Issue by silhouettes** [SBoudrias/gulp-exclude-gitignore#2]
For example, if my gulp script is running from directory `a/`, and I have a .gitignore in directory `a/b/`, and I run `excludeGitignore("b/.gitignore")`, it will prefix the patterns in the .gitignore with just `a/` instead of `a/b/`.

I think that what we should actually do is resolve the full path of the gitignore and prefix the patterns with the parent directory of the .gitignore, wherever it is in the file system. Alternatively, we could specify an option to override either the prefix or the current working directory.

**Comment by SBoudrias** [comment]
PR welcomed!
