### ISSUE TITLE
Arrow Function

### ISSUE THREAD

**Issue by danmademe** [SBoudrias/gulp-exclude-gitignore#5]
Line 26 of your index you're using a arrow function, this will break on older versions of node.

` .map(str => str.trim())`

If possible can you please use babel and create a dist folder with non es6 for older versions?

if you want me to do it let me know

**Comment by SBoudrias** [comment]
Node v4 has been out for over a year. Any reason you don't upgrade?

**Comment by danmademe** [comment]
Oh I've upgraded, however since you're library is used in a yeoman npm module generator, specifically for making es6 node modules output to commonJS, it's a bit hard to run it though a battery of unit tests for different versions of node. So a CI will fail tests under node v4..

It's not difficult to set it up your library so that it would output commonJS to a dist folder. You can keep writing JS any way you like and have babel transpile it for you 😄 

If you want me to do that for you thats no problem

**Comment by SBoudrias** [comment]
> however since you're library is used in a yeoman npm module generator

Yeah, I wrote it ;)

I reverted the arrow functions.
